const keys = {
  firstRow: [
    { '`': '' },
    { 1: '' },
    { 2: '' },
    { 3: '' },
    { 4: '' },
    { 5: '' },
    { 6: '' },
    { 7: '' },
    { 8: '' },
    { 9: '' },
    { 0: '' },
    { '-': '' },
    { '=': '' },
    { Backspace: ['keyboard-button--service', 'keyboard-button--backspace'] },
  ],
  secondRow: [
    { Tab: ['keyboard-button--service', 'keyboard-button--caps-tab'] },
    { q: '' },
    { w: '' },
    { e: '' },
    { r: '' },
    { t: '' },
    { y: '' },
    { u: '' },
    { i: '' },
    { o: '' },
    { p: '' },
    { '[': '' },
    { ']': '' },
    { '\\': '' },
  ],
  thirdRow: [
    { 'Caps Lock': ['keyboard-button--service', 'keyboard-button--caps-lock'] },
    { a: '' },
    { s: '' },
    { d: '' },
    { f: '' },
    { g: '' },
    { h: '' },
    { j: '' },
    { k: '' },
    { l: '' },
    { ';': '' },
    { "'": '' },
    { Enter: ['keyboard-button--service', 'keyboard-button--enter'] },
  ],
  fourthRow: [
    { Shift: ['keyboard-button--service', 'keyboard-button--shift'] },
    { z: '' },
    { x: '' },
    { c: '' },
    { v: '' },
    { b: '' },
    { n: '' },
    { m: '' },
    { ',': '' },
    { '.': '' },
    { '/': '' },
    { "'": '' },
    { Shift: ['keyboard-button--service', 'keyboard-button--shift'] },
  ],
  fifthRow: [
    { Ctrl: ['keyboard-button--service', 'keyboard-button--ctrl'] },
    { Win: ['keyboard-button--service', 'keyboard-button--win'] },
    { Alt: ['keyboard-button--service', 'keyboard-button--alt'] },
    { Space: ['keyboard-button--service', 'keyboard-button--space'] },
    { Alt: ['keyboard-button--service', 'keyboard-button--alt'] },
    { Win: ['keyboard-button--service', 'keyboard-button--win'] },
    { Ctrl: ['keyboard-button--service', 'keyboard-button--ctrl'] },
  ],
};

export default keys;
